const PD = [
    {
        id: 1,
        title: "부산관광공사",
        en: "Busan Tourism Organization",
        src: "/img/pfimg01.png",
        link: "https://chae-g-0.github.io/test11/",
        code: "https://github.com/Chae-G-0/test11",
        anchor: "Portfolio01",
        des: "리엑트를 이용한 부산관광공사 홈페이지 (SPA)",
        type: "메인 페이지 + 서브 페이지",
        date: "2022.09.30 ~ 2022.10.11",
        font: "Spoqa Han Sans",
        tools: "react + scss",
        contribution: "100%",
    },

    {
        id: 2,
        title: "서울대학교",
        en: "Seoul National University",
        src: "/img/pfimg02.png",
        link: "https://chae-g-0.github.io/test10/",
        code: "https://github.com/Chae-G-0/test10",
        anchor: "Portfolio02",
        des: "리엑트를 이용한 서울대학교 홈페이지",
        type: "메인 페이지",
        date: "2022.09.19 ~ 2022.09.23",
        font: "Noto Sans KR",
        tools: "react + scss",
        contribution: "100%",
    },
    {
        id: 3,
        title: "잭슨카멜레온",
        en: "Jackson Chameleon",
        src: "/img/pfimg03.png",
        link: "https://chae-g-0.github.io/test07/",
        code: "https://github.com/Chae-G-0/test07",
        anchor: "Portfolio03",
        des: "바닐라 자바스크립트를 이용한 잭슨카멜레온 홈페이지",
        type: "메인 페이지",
        date: "2022.08.22 ~ 2022.08.26",
        font: "Spoqa Han Sans Neo + Cormorant Garamond",
        tools: "html + css + javascript",
        contribution: "100%",
    },
    {
        id: 4,
        title: "블루샥",
        en: "Blu shaak",
        src: "/img/pfimg04.png",
        link: "https://chae-g-0.github.io/test06/",
        code: "https://github.com/Chae-G-0/test06",
        anchor: "Portfolio04",
        des: "블루샥 홈페이지",
        type: "메인 페이지(반응형)",
        date: "2022.08.08 ~ 2022.08.19",
        font: "Spoqa Han Sans Neo + Cormorant Garamond",
        tools: "html + css + Jquery",
        contribution: "100%",
    },

    {
        id: 5,
        title: "에스쁘아",
        en: "Espoir",
        src: "/img/pfimg05.png",
        link: "https://chae-g-0.github.io/test03/",
        code: "https://github.com/Chae-G-0/test03",
        anchor: "Portfolio05",
        des: "에스쁘아 홈페이지",
        type: "메인 페이지",
        date: "2022.07.11 ~ 2022.07.15",
        font: "Noto Sans KR + Libre Baskerville",
        tools: "html + css + Jquery",
        contribution: "100%",
    },
];

export default PD;
